### PR TITLE
Propagate tags via par_*** macros

### PR DESCRIPTION
**Pull request by andyscott**
This updates the `par_***` macros to propagate tags to the underlying rules. This is important, as currently the `manual` tag doesn't work fro the `par_***` macros.

### CODE REVIEW

**Comment by johnynek** [comment]
@dkelmer you seem to have merged things lately. Can we get a review of this?

We are keeping a fork to fix this issue.

Also, what is the process to get reviews? Is 18 days the normal length of time to wait or is someone out or something?

**Comment by jin** [comment]
@brandjon ping, please take a look.

**Comment by jin** [comment]
Also, what's the status of this repository? Is it in maintenance mode? Can we update the README / description to reflect it as such?

**Comment by johnynek** [comment]
Thank you very much! This is a big help to keep our engineers motivated to send PRs!

**Pull request merged**
