### PR TITLE
Make par_binary respect visibility

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes https://github.com/google/subpar/issues/23

### CODE REVIEW

**Comment by mattmoor** [comment]
@duggelz FYI

**Comment by duggelz** [comment]
Looks like I need to fix the Travis config again.

**Comment by mattmoor** [comment]
This looks like a ~recent change to require `cfg="host"` or somesuch on executable rules.  I'd guess this is just using an older set of rules (sass.bzl) with a newer Bazel release.

**Comment by mattmoor** [comment]
@damienmg FYI

**Pull request merged**
