### PR TITLE
Cleanup for Bazel future changes

### PR DESCRIPTION
**Pull request by laurentlb**
Tested:
  `bazel0.20 test //... --all_incompatible_changes`

- Reformatted file with Buildifier
- Applied Buildifier automated fixes
- Fixed other issues (depsets are not iterable, tools are separate from other inputs)

Progress towards https://github.com/bazelbuild/rules_python/issues/134

### CODE REVIEW

**Comment by laurentlb** [comment]
cc @brandjon

**Comment by laurentlb** [comment]
The first commit is the reformatting.
Diff might be easier to read if you skip it: https://github.com/google/subpar/pull/88/files/fe1e114d107b3bf46a5bf035d1e1c3cdc47202e2..9662e6b5fafb273bcd37b55ea70c0a539e009e6a

**Comment by brandjon** [comment]
I think this actually falls on me to maintain, but I need to get commit rights to this repo.

**Comment by laurentlb** [comment]
Who's maintaining this repository?

**Comment by laurentlb** [comment]
@brandjon - please merge

**Comment by brandjon** [comment]
Thanks Laurent.

**Pull request merged**
