### PR TITLE
Add par_test variant of par_binary, passthrough testonly attr

### PR DESCRIPTION
**Pull request by benley**
This makes it possible to run py_tests as .par files, which is occasionally useful for testing code that behaves differently when called from within a zipped executable.  It also enables the uncommon (but valid, I'm pretty sure) scenario of having a par_binary definition with `testonly=True` set.

### CODE REVIEW

**Comment by duggelz** [comment]
Thanks for this merge request!  It'll take me a couple of days to review this, due to some other issues that I'm working on right now.

We'll want to add some sample par_test targets to the tests/ subdirectory as well.

**Comment by duggelz** [comment]
Sorry, still trying to deal with some other Bazel breakages.

**Comment by benley** [comment]
awesome, thank you :-)

**Comment by duggelz** [comment]
Thanks for your pull request, merged.  I have to do some refactoring to address Bazel changes, so I'll add tests for this at the same time.

**Pull request merged**
